### ISSUE TITLE
Short ping interval of 1s occasionally  causes disconnect errors that are generated repeatedly.

### ISSUE THREAD

**Issue by igoberman** [nats-io/java-nats#226] opened 2019-04-04 17:43 UTC
Hello, we encountered a problem with jnats 2.4.2: if ping set to 1s, once in a while we start getting error "Exception Max outgoing Ping count exceeded"/ " Exception Socket closed". Once this happens, we start getting connection event DISCONNECTED repeatedly and our log is bombarded with messages below. Also, looks like connection actually stays up.
It is difficult to duplicate, but it looks like it did not happen prior to 2.4.2.

2019-04-04T11:41:06.415 [pool-11-thread-1] ERROR c.b.f.f.components.openfeed.OFReader - io.nats.client.impl.NatsConnection@5932d3d9: Exception Max outgoing Ping count exceeded.
2019-04-04T11:41:06.420 [pool-11-thread-1] INFO  c.b.f.f.components.openfeed.OFReader - NATS: connection event - nats: connection disconnected
2019-04-04T11:41:06.444 [pool-8-thread-1] ERROR c.b.f.f.components.openfeed.OFReader - io.nats.client.impl.NatsConnection@4054bdb7: Exception Max outgoing Ping count exceeded.
2019-04-04T11:41:06.446 [pool-8-thread-1] INFO  c.b.f.f.components.openfeed.OFReader - NATS: connection event - nats: connection disconnected
2019-04-04T11:41:06.498 [pool-11-thread-1] ERROR c.b.f.f.components.openfeed.OFReader - io.nats.client.impl.NatsConnection@5932d3d9: Exception Socket closed
2019-04-04T11:41:06.498 [pool-11-thread-1] INFO  c.b.f.f.components.openfeed.OFReader - NATS: connection event - nats: connection disconnected
2019-04-04T11:41:09.525 [pool-8-thread-1] ERROR c.b.f.f.components.openfeed.OFReader - io.nats.client.impl.NatsConnection@4054bdb7: Exception Socket closed
2019-04-04T11:41:09.525 [pool-8-thread-1] INFO  c.b.f.f.components.openfeed.OFReader - NATS: connection event - nats: connection disconnected
2019-04-04T11:41:10.576 [pool-11-thread-1] ERROR c.b.f.f.components.openfeed.OFReader - io.nats.client.impl.NatsConnection@5932d3d9: Exception Socket closed
2019-04-04T11:41:10.577 [pool-11-thread-1] INFO  c.b.f.f.components.openfeed.OFReader - NATS: connection event - nats: connection disconnected
2019-04-04T11:41:10.593 [pool-8-thread-1] ERROR c.b.f.f.components.openfeed.OFReader - io.nats.client.impl.NatsConnection@4054bdb7: Exception Socket closed
2019-04-04T11:41:10.593 [pool-8-thread-1] INFO  c.b.f.f.components.openfeed.OFReader - NATS: connection event - nats: connection disconnected
2019-04-04T11:41:11.646 [pool-11-thread-1] ERROR c.b.f.f.components.openfeed.OFReader - io.nats.client.impl.NatsConnection@5932d3d9: Exception Socket closed
2019-04-04T11:41:11.647 [pool-11-thread-1] INFO  c.b.f.f.components.openfeed.OFReader - NATS: connection event - nats: connection disconnected
2019-04-04T11:41:11.675 [pool-8-thread-1] ERROR c.b.f.f.components.openfeed.OFReader - io.nats.client.impl.NatsConnection@4054bdb7: Exception Socket closed
2019-04-04T11:41:11.675 [pool-8-thread-1] INFO  c.b.f.f.components.openfeed.OFReader - NATS: connection event - nats: connection disconnected

**Comment by sasbury** [comment] 2019-04-04 22:07
I will take a look tomorrow, we removed one extra error and I wonder if
that was saving us somehow

**Comment by sasbury** [comment] 2019-04-05 17:45
ok, trying to look today - i think the issue may have shown up in other places as well. I just merged a PR into the 2.4.3 branch that i have a feeling may fix your issue. If you get a chance to try the branch I would be curious if it fixes things. Otherwise I will try to reproduce and test on my side.

**Comment by sasbury** [comment] 2019-04-05 18:21
i have a unit tests with 5ms pings that isn't having the problem, so I added a version that disconnects and reconnects, and it still seems to be ok. Can you give me some more context so I can try to reproduce, or if you see that branch 2.4.3 fixes it, then I guess we are good to go?

**Comment by igoberman** [comment] 2019-04-08 19:26
Can you put in mvn? I do not want to build it myself.

**Comment by sasbury** [comment] 2019-04-09 20:48
i released 2.4.3 today, should be on maven central by end of day. If the ping issue continues we can fix in 2.4.4

**Comment by igoberman** [comment] 2019-04-17 14:46
There is still some issue with reconnects. We have nats running on local host. Today somehow connection was reset and API generated exceptions below. Last one was CancellationException related to cleanUpPongQueue. NATS never reconnected after that.


2019-04-17T09:30:12.346 [pool-4-thread-1] ERROR c.b.o.c.nats.NatsConnectionProvider - Nats 'nats://127.0.0.1:4222' exception: {}
java.net.SocketException: Connection reset
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at io.nats.client.impl.SocketDataPort.write(SocketDataPort.java:104)
        at io.nats.client.impl.NatsConnectionWriter.run(NatsConnectionWriter.java:160)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-04-17T09:30:12.411 [pool-4-thread-1] ERROR c.b.o.c.nats.NatsConnectionProvider - Nats 'null' exception: {}
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at io.nats.client.impl.SocketDataPort.read(SocketDataPort.java:100)
        at io.nats.client.impl.NatsConnectionReader.run(NatsConnectionReader.java:111)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-04-17T09:30:12.413 [pool-4-thread-1] INFO  c.b.o.c.nats.NatsConnectionProvider - NATS: connection event - nats: connection disconnected
2019-04-17T09:30:12.419 [pool-4-thread-1] INFO  c.b.o.c.nats.NatsConnectionProvider - NATS: connection event - nats: discovered servers
2019-04-17T09:30:12.525 [pool-4-thread-1] ERROR c.b.o.c.nats.NatsConnectionProvider - Nats 'null' exception: {}
java.util.concurrent.CancellationException: null
        at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
        at io.nats.client.impl.NatsConnection.cleanUpPongQueue(NatsConnection.java:618)
        at io.nats.client.impl.NatsConnection.closeSocketImpl(NatsConnection.java:599)
        at io.nats.client.impl.NatsConnection.closeSocket(NatsConnection.java:472)
        at io.nats.client.impl.NatsConnection.lambda$handleCommunicationIssue$2(NatsConnection.java:445)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-04-17T09:30:12.527 [pool-4-thread-1] INFO  c.b.o.c.nats.NatsConnectionProvider - NATS: connection event - nats: connection disconnected

**Comment by sasbury** [comment] 2019-05-07 23:57
See #231 for more comments, but I think the short ping is ultimately a config error and added some documentation. The reconnect failure is not a config error, but I think i fixed that (more on the other issue.)

**Closed** 2019-05-09 20:40 UTC
